apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: service-b
  name: service-b
  namespace: service-b
data:
  BACKEND_ENABLED: "False" # flag to enable backend service call "False" || "True"
  # when defining the BACKEND_SERVICE using an HTTP protocol, indicate HTTP or HTTPS; if using gRPC, use the host name only
  BACKEND_SERVICE: "http://service-b-backend" # substitute with corresponding service name - this example assumes both services are in the same namespace  
  METADATA:        "service-b" # arbitrary string that gets returned in payload - can be used to track which services you're interacting with 
  ECHO_HEADERS:    "False" # flag to enable the payload including all headers received in the `echo_headers` field if set to "True"
  GRPC_ENABLED:    "False" # flag to switch service-b service to gRPC mode
  TRACE_SAMPLING_RATIO: "0.00" # trace sampling ratio; i.e. the % likelyhood a trace will be sent to Cloud Trace; setting to zero disables tracing; expects float. "0.10" == 10%
# [END gke_k8s_configmap_configmap_service-b_configmap]